export const LOADING_CONTACTS = 'LOADING_CONTACTS';
export const LOAD_CONTACTS = 'LOAD_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const SUBMIT_CONTACT = 'SUBMIT_CONTACT';
export const FINISH_EDIT_CONTACT = 'FINISH_EDIT_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SELECT_CONTACT = 'SELECT_CONTACT';
